#!/bin/bash
# =============================================================================
#  Leoxur Employee Management Portal — Deployment Script
#  Run this script on the server to deploy or redeploy the application.
#  Usage: bash deploy.sh
# =============================================================================

set -e

echo ""
echo "============================================================"
echo "  Employee Time & Management Portal — Deployment Setup"
echo "============================================================"
echo ""

# --- Prompt for Organization / Application Name ---
while true; do
    read -p "  Enter your organization name (e.g. Acme Corp): " ORG_NAME
    ORG_NAME="$(echo "$ORG_NAME" | xargs)"   # trim whitespace
    if [ -n "$ORG_NAME" ]; then
        break
    fi
    echo "  ⚠️  Organization name cannot be empty. Please try again."
done

echo ""
echo "  ✅  Organization name set to: \"$ORG_NAME\""
echo ""

# --- Write .env file ---
cat > .env <<EOF
# Auto-generated by deploy.sh on $(date)
APP_NAME=${ORG_NAME}
EOF

echo "  📄  .env file written."
echo ""

# --- Pull latest code (optional, skip if running from cloned dir) ---
if git rev-parse --git-dir > /dev/null 2>&1; then
    echo "  🔄  Pulling latest code from Git..."
    git pull origin main
    echo ""
fi

# --- Build and start Docker containers ---
echo "  🐳  Building and starting Docker containers..."
docker-compose up --build -d

echo ""
echo "  ⏳  Waiting for the container to be ready..."
sleep 5

# --- Apply database migrations ---
echo "  🗄️   Applying database migrations..."
docker-compose exec web python manage.py migrate

echo ""
echo "  👤  Create the first superuser (admin) account:"
docker-compose exec web python manage.py createsuperuser

echo ""
echo "============================================================"
echo "  ✅  Deployment complete!"
echo ""
echo "  Your portal is now running at: http://$(hostname -I | awk '{print $1}')/"
echo ""
echo "  Next steps:"
echo "  1. Open the URL above in your browser."
echo "  2. Log in at /admin/ to add departments, avatar options,"
echo "     and create IT support groups."
echo "  3. Log in at /manager/login/ to start adding employees."
echo "============================================================"
echo ""
