#!/bin/bash
# =============================================================================
#  Leoxur Employee Management Portal — Deployment Script
#  Run this script on the server to deploy or redeploy the application.
#  Usage: bash deploy.sh
# =============================================================================

set -e

echo ""
echo "============================================================"
echo "  Employee Time & Management Portal — Deployment Setup"
echo "============================================================"
echo ""

# --- Prompt for Organization / Application Name ---
while true; do
    read -p "  Enter your organization name (e.g. Acme Corp): " ORG_NAME
    ORG_NAME="$(echo "$ORG_NAME" | xargs)"   # trim whitespace
    if [ -n "$ORG_NAME" ]; then
        break
    fi
    echo "  ⚠️  Organization name cannot be empty. Please try again."
done

echo ""
echo "  ✅  Organization name set to: \"$ORG_NAME\""
echo ""

# --- Prompt for Database Engine ---
DB_ENGINE="sqlite"
while true; do
    read -p "  Do you want to use MySQL database instead of SQLite? (y/n) [n]: " USE_MYSQL
    USE_MYSQL="$(echo "$USE_MYSQL" | tr '[:upper:]' '[:lower:]')"
    if [ "$USE_MYSQL" = "y" ] || [ "$USE_MYSQL" = "yes" ]; then
        DB_ENGINE="mysql"
        break
    elif [ "$USE_MYSQL" = "n" ] || [ "$USE_MYSQL" = "no" ] || [ -z "$USE_MYSQL" ]; then
        break
    fi
    echo "  ⚠️  Please enter 'y' or 'n'."
done

if [ "$DB_ENGINE" = "mysql" ]; then
    read -p "  Enter MySQL Database Host (use 'db' for containerized MySQL) [db]: " DB_HOST
    DB_HOST="${DB_HOST:-db}"
    read -p "  Enter MySQL Database Port [3306]: " DB_PORT
    DB_PORT="${DB_PORT:-3306}"
    read -p "  Enter MySQL Database Name [employee_manage]: " DB_NAME
    DB_NAME="${DB_NAME:-employee_manage}"
    read -p "  Enter MySQL User [employee_user]: " DB_USER
    DB_USER="${DB_USER:-employee_user}"
    read -sp "  Enter MySQL Password: " DB_PASSWORD
    echo ""
fi

# --- Write .env file ---
cat > .env <<EOF
# Auto-generated by deploy.sh on $(date)
APP_NAME=${ORG_NAME}
DB_ENGINE=${DB_ENGINE}
EOF

if [ "$DB_ENGINE" = "mysql" ]; then
    cat >> .env <<EOF
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
EOF
    echo "  📄  .env file written with MySQL configuration."
else
    echo "  📄  .env file written with SQLite configuration."
fi
echo ""

# --- Pull latest code (optional, skip if running from cloned dir) ---
if git rev-parse --git-dir > /dev/null 2>&1; then
    echo "  🔄  Pulling latest code from Git..."
    git pull origin main || echo "  ⚠️  Could not pull latest code; continuing with local files."
    echo ""
fi

# --- Build and start Docker containers ---
echo "  🐳  Building and starting Docker containers..."
docker-compose up --build -d

# --- Wait for database service to be ready ---
echo "  ⏳  Waiting for database connection to be established..."
MAX_ATTEMPTS=30
ATTEMPT=1
until docker-compose exec -T web python -c "
import os, sys, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'employee_attendance.settings')
django.setup()
from django.db import connections
from django.db.utils import OperationalError
try:
    connections['default'].cursor()
    sys.exit(0)
except OperationalError:
    sys.exit(1)
" >/dev/null 2>&1; do
    if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
        echo "  ❌  Error: Database did not become ready in time."
        exit 1
    fi
    echo "  ... waiting for database ($ATTEMPT/$MAX_ATTEMPTS) ..."
    sleep 2
    ATTEMPT=$((ATTEMPT + 1))
done

# --- Apply database migrations ---
echo "  🗄️   Applying database migrations..."
docker-compose exec web python manage.py migrate

echo ""
echo "  🌱  Seeding required configuration options..."
docker-compose exec web python manage.py seed_configurations

echo ""
echo "  👤  Create the first superuser (admin) account:"
docker-compose exec web python manage.py createsuperuser

echo ""
echo "============================================================"
echo "  ✅  Deployment complete!"
echo ""
echo "  Your portal is now running at: http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost')/"
echo ""
echo "  Next steps:"
echo "  1. Open the URL in your browser."
echo "  2. Log in at /admin/ to add departments, avatar options,"
# manager_login and manager_dashboard references updated
echo "  3. Log in at /manager/login/ to start adding employees."
echo "============================================================"
echo ""
