# Generated by Django 4.2.30 on 2026-06-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leoxuremail_leoxurmeeting_leoxurmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeoxurMeeting',
        ),
        migrations.AddField(
            model_name='leoxurmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='attendance.leoxurmessage'),
        ),
    ]
