# Generated by Django 4.2.30 on 2026-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_delete_leoxurmeeting_leoxurmessage_parent_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeoxurTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('highest', 'Highest')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], default='backlog', max_length=15)),
                ('creator_id', models.CharField(max_length=50)),
                ('assignee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
