# Generated by Django 4.2.30 on 2026-06-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leoxurtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leoxurtask',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done'), ('archived', 'Archived')], default='backlog', max_length=15),
        ),
        migrations.CreateModel(
            name='LeoxurTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='attendance.leoxurtask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
