# Generated by Django 4.2.30 on 2026-06-27 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_departmentoption_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='leoxuremail',
            name='cc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pin_code',
            field=models.CharField(default='123456', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'PIN code must be exactly 6 digits.')]),
        ),
    ]
